config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users,
  :path => '', 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  :controllers=>{:registrations=> 'registrations', 
                :confirmations=> 'confirmations'}

root 'pages#home'

resources :users, only: [:show]
resources :rooms,  path: 'annonces' do 
resources :reservations, only: [:create]
resources :reviews, only: [:create, :destroy]
end
resources :photos
resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
end

get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'

get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

get '/search' => 'pages#search'

end

app/views/pages/home.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="text-center">
            <h1>Réservez des logements uniques et vivez votre destination comme un habitant.</h1>
        </div>
    </div>
</div>
<br>
<%= form_tag search_path, method: :get do %>
    <div class="row">
        <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: "Où? Destination, ville, adresse",
            class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :start_date, params[:start_date], placeholder:"Arrivée", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :end_date, params[:end_date], placeholder:"Départ", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= submit_tag "Rechercher", class:"btn btn-primary" %>
        </div>
    </div>
<% end %>
<br>
<hr>
<br>
<div class="row">
    <div class="col-md-4">
        <h4>Logements</h4>
    </div>
</div>
<div class="row">
    <% @rooms.each do |room| %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading preview">
                    <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                </div>
                <div class="panel-body">
                    <p class="home-link"><b><%= link_to room.price, room_path(room) %> € - <%= link_to room.room_type, room_path(room) %> - <%= link_to pluralize(room.bed_room, "lit"), room_path(room) %></b>
                    <br><%= link_to room.listing_name, room_path(room) %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        });
        
        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>

app/views/pages/search.html.erb
<div id="wrapper">
    <div id="sidebar">
        <div id="widget">

        </div>
    </div>
    <div id="article">
        <div class="row">
            <div class="col-md-12">
                <%= search_form_for @search, url: search_path do |f| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= text_field_tag :start_date, params[:start_date], placeholder:"Arrivée", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= text_field_tag :end_date, params[:end_date], placeholder:"Départ", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_gteq, placeholder: "Budget min", class: "form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_lteq, placeholder: "Budget max", class: "form-control" %>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Logement entier" %> Logement entier
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Chambre privée" %> Chambre privée
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","Chambre partagée" %> Chambre partagée
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Voyageurs ?</label>
                                <%= f.select :accommodate_gteq, [["1 voyageur",1],["2 voyageurs",2],
                                ["3 voyageurs",3], ["4 voyageurs",4] ,["5 voyageurs",5],
                                ["6 voyageurs",6]], prompt:"A sélectionner...",
                                class:"form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Chambres ?</label>
                                <%= f.select :bed_room_gteq, [["1",1],["2",2],
                                ["3",3], ["4",4]], prompt:"A sélectionner...",
                                class:"form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Salles de bain ?</label>
                                <%= f.select :bath_room_gteq, [["1",1],["2",2],
                                ["3",3], ["4",4]], prompt:"A sélectionner...",
                                class:"form-control" %>
                            </div>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_wifi_eq]", true %> Wifi
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_tv_eq]", true %> Télévision
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_closet_eq]", true %> Penderie
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_shampoo_eq]", true %> Shampoing
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_kitchen_eq]", true %> Cuisine
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_breakfast_eq]", true %> Petit déjeuner
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_heating_eq]", true %> Chauffage
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_air_eq]", true %> Climatisation
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <%= f.submit "Rechercher", class:"btn btn-primary" %>
                    </div>


                <% end %>

                <hr>



                <div class="row">
                    <% if @arrRooms.empty? %>
                        Aucune annonce ne correpond à votre recherche.
                    <% else %>
                        <% @arrRooms.each do |room| %>
                        <div class="col-md-4">
                            <div class="panel panel-default">
                                <div class="panel-heading preview">
                                    <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                                </div>
                                <div class="panel-body">
                                    <%= image_tag avatar_url(room.user), class:"img-circle avatar-small" %>
                                    <%= link_to room.listing_name, room %>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        })

        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>