config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users,
  :path => '', 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  :controllers=>{:registrations=> 'registrations', 
                :confirmations=> 'confirmations'}

root 'pages#home'

resources :users, only: [:show]
resources :rooms,  path: 'annonces' do 
resources :reservations, only: [:create]
resources :reviews, only: [:create, :destroy]
end
resources :photos
resources :conversations, only: [:index, :create] do
  resources :messages, only: [:index, :create]
end

get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'

get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

get '/search' => 'pages#search'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_one :payment
  accepts_nested_attributes_for :payment
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
 
before_action :authenticate_user! 


def preload
  room = Room.find(params[:room_id])
  today = Date.today
  reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)
  
  render json: reservations
end




def preview
   start_date = Date.parse(params[:start_date])
   end_date = Date.parse(params[:end_date])
   
   output = {
       conflict: is_conflict(start_date, end_date)
   }
   
   render json: output
end

def create
 
    @reservation = current_user.reservations.create(reservation_params)

    if @reservation.persisted?
           @payment = Payment.new({ email: User.find(@reservation.user_id).email, 
            token: params[:payment]["token"], reservation_id: @reservation.id, 
            amount: @reservation.total }) #on teste d’abord la création d’un paiement avec les renseignements de la réservation (email, prix total) et du champ carte bleue
           
           begin # process du paiement

           @payment.process_payment

                   if @payment.save

                        AppMailer.new_reservation(Room.find(@reservation.room_id), @reservation).deliver_now

                        redirect_to @reservation.room, notice: "Votre réservation a été acceptée"

                   end
           
           rescue Exception  

        
           puts 'Le paiement a échoué'
           redirect_to @reservation.room, notice: "Votre paiement a été refusé"

           end
     else
             redirect_to @reservation.room, notice: "Votre réservation a échoué"
     end

end
 
def your_trips
 
  @trips = current_user.reservations 

end
  
def your_reservations
  
    @rooms = current_user.rooms
end
  
private
 
     def reservation_params         
        params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id, :payment)     
     end 
end

private
    def is_conflict(start_date, end_date)
        room = Room.find(params[:room_id])
 
        check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
        check.size > 0? true : false
    end

app/views/reservations/_form.html.erb
<%= form_for([@room,  @room.reservations.new], html: { class: 'cc_form'}) do |f| %>     
 
    <div class="row">
        <div class="col-md-12 price_tag">
            <span>€ <%= @room.price %></span>
            <span class="pull-right">Par nuit</span>
        </div>
    </div>
     <div class="row">
         <div class="col-md-6">
         <label>Arrivée</label>
         <%= f.text_field :start_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>
         </div>
 
         <div class="col-md-6">
         <label>Départ</label>
         <%= f.text_field :end_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>
         </div>
      </div>
     
     <h5><div id="message"></div></h5> 

      <div id="preview" style="display: none">
           <table class="reservation-table" >
                   <tbody>
                        <tr>
                            <td>Nuit(s)</td>
                            <td><span id="reservation_days"></span></td>
                        </tr>
                        <tr>
                             <td>Total</td>
                             <td><span id="reservation_sum"></span>€</td>
                       </tr>
                   </tbody>
            </table>

            <br>
     <h5><span id="stripe"><span></h5>
     
     <%= fields_for( :payment ) do |p| %>
      <div class="row">
           <div class="col-md-12">
                <div class="form-group col-md-9">
                      <%= p.label :card_number, "Numéro CB", data: { stripe: 'label'} %>
                      <%= p.text_field :card_number, class: "form-control", required: true, data: { stripe: 'number'} %>
              </div>
              <div class="form-group col-md-3">
                   <%= p.label :card_cvv, "CVV", data: { stripe: 'label'} %>
                   <%= p.text_field :card_cvv, class: "form-control", required: true, data: { stripe: 'cvv'} %>
               </div>
          </div>
         <div class="col-md-10">
              <div class="col-md-12">
                 <%= p.label :card_expires, "Expire fin :", data: { stripe: 'label'} %>
              </div>
              <div class="form-group col-md-5">
                  <%= p.select :card_expires_month, options_for_select(Payment.month_options), { include_blank: 'Mois' }, "data-stripe" => "exp-month", class: "form-control", required: true %>
              </div>
              <div class="form-group col-md-6">
                      <%= p.select :card_expires_year, options_for_select(Payment.year_options.push), { include_blank: 'Année' }, class: "form-control", data: { stripe: "exp-year" }, required: true %>
              </div>
          </div>
     </div>
     </div>

     <% end %>
 
 
     <%= f.hidden_field :room_id, value: @room.id %> 
     <%= f.hidden_field :price, value: @room.price %>
     <%= f.hidden_field :total, id: 'reservation_total' %>
     
    <br>
 
     <%= f.submit "Demande de réservation", id:" btn_book", class: "btn btn-primary wide" %>
 
 <% end %>

<script>
    function unavailable(date) {
        dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
        return [$.inArray(dmy, unavailableDates) == -1];
    }
    $(function(){
        
        unavailableDates = [];
        
        $.ajax({
            url: '/preload',
            data: {'room_id': <%= @room.id %>},
            dataType: 'json',
            success: function(data) {
                $.each(data, function(arrID, arrValue){
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date);
                    d.setDate(d.getDate() +1)) {
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                })
                
                $('#reservation_start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#reservation_end_date').datepicker("option","minDate", newdate);
                        $('#reservation_end_date').attr('disabled', false);
                        
                        var start_date = $(this).datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);
                        
                        
                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                            
                        }
                            
                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);
                                        
                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }
                                
                                }
                            });
                        
                    }
                });
                
                $('#reservation_end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        $('#reservation_start_date').datepicker("option", "maxDate", selected);
                        
                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $(this).datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);
                        
                        
                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                            
                        }
                            
                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("Ces dates sont indisponibles");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);
                                        
                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }
                                
                                }
                            });
                        
                    }
                });
                
            }
        });
        
        
    });
</script>

<script language="Javascript">
 
 Stripe.setPublishableKey('pk_test_8gxzt7G69zlvLnrAzV1Hcc9S');
 
 </script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes réservations</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= reservation.start_date.strftime('%d.%m.%y') %> au <%= reservation.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.user) do %>
                           <%= image_tag avatar_url(reservation.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes voyages</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.strftime('%d.%m.%y') %> au <%= trip.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>